apiVersion: v1
kind: Service
metadata:
  name: redmine
spec:
  ports:
  - port: 3000
  selector:
    app: redmine
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: redmine
spec:
  selector:
    matchLabels:
      app: redmine
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
      - image: redmine
        name: redmine
        env:
          # Use secret in real usage
        - name: REDMINE_DB_POSTGRES
          value: pgsql-postgresql.pgsql.svc.cluster.local
        - name: REDMINE_DB_DATABASE
          value: redmine
        - name: REDMINE_DB_USERNAME
          value: postgres
        - name: REDMINE_DB_PASSWORD
          value: OKF50MxwMx
        ports:
        - containerPort: 3000
          name: redmine
        volumeMounts:
        - name: redmine-persistent-storage
          mountPath: /var/lib/redmine
      volumes:
      - name: redmine-persistent-storage
        persistentVolumeClaim:
          claimName: redmine-pv-claim
